import fs from 'fs';
import path from 'path';

const outDir = 'C:/Users/Lux/thai-generator/ai-server/admin-data/generated-candidates';

const lessons = {
  'endurance-wai': {
    stage: 'A2.2',
    lessonTitle: 'Endurance and Capacity with ไหว / ไม่ไหว',
    rows: [
      { thai: 'เดินกลับจากสถานีอีกหน่อยก็ยังไหว', english: 'I can still walk a bit farther from the station.' },
      { thai: 'ถือถุงสองใบพร้อมกันไม่ไหวแล้ว มันหนักเกิน', english: "I can't carry both bags anymore. They're too heavy." },
      { thai: 'วันนี้ง่วงมาก ดูซีรีส์ต่อไม่ไหวแล้ว', english: "I'm too sleepy to keep watching the series tonight." },
      { thai: 'รอคิวอีกครึ่งชั่วโมงฉันยังไหว', english: 'I can handle another half hour in line.' },
      { thai: 'อากาศร้อนขนาดนี้ออกไปวิ่งไม่ไหวหรอก', english: "It's too hot to go running in this weather." },
      { thai: 'วันนี้งานเยอะมาก ทำต่อไม่ไหวแล้ว', english: "There's too much work today. I can't keep going." },
      { thai: 'แกงถ้วยนี้เผ็ด แต่ฉันยังกินไหว', english: 'This curry is spicy, but I can still eat it.' },
      { thai: 'วันนี้ฉันเหนื่อยมาก ไปต่อร้านที่สองไม่ไหว', english: "I'm really tired today. I can't go to a second place after this." },
      { thai: 'วิ่งอีกสองรอบฉันยังไหว', english: 'I can still do two more laps.' },
      { thai: 'เดินดูของต่ออีกสามชั่วโมงไม่ไหวแล้ว', english: "I can't keep shopping for another three hours." },
      { thai: 'อ่านหนังสือต่อไม่ไหวแล้ว สมองไม่รับแล้ว', english: "I can't keep studying. My brain's done." },
      { thai: 'ยืนบนรถเมล์อีกสิบนาทียังไหว', english: 'I can still stand on the bus for another ten minutes.' },
      { thai: 'ขึ้นบันไดอีกชั้นไม่ไหวแล้ว ขาสั่นหมดแล้ว', english: "I can't climb another floor. My legs are shaking." },
      { thai: 'ประชุมต่ออีกชั่วโมงฉันยังไหวอยู่', english: 'I can handle another hour of meetings.' },
      { thai: 'ทำความสะอาดบ้านทั้งหลังคนเดียวไม่ไหว', english: "I can't clean the whole house by myself." },
      { thai: 'เดินเที่ยวทั้งวันแบบนี้ พรุ่งนี้คงไม่ไหว', english: "After walking around all day like this, I probably won't have it in me tomorrow." },
      { thai: 'ขับรถต่อถึงเชียงใหม่คืนนี้ยังไหวไหม', english: 'Can you still handle driving all the way to Chiang Mai tonight?' },
      { thai: 'อยู่ในห้องที่เสียงดังแบบนี้ไม่ไหวจริงๆ', english: "I really can't stand being in a room this noisy." },
      { thai: 'เป็นหวัดแบบนี้จะให้ไปทำงานก็ไม่ไหว', english: "With a cold like this, I can't go in to work." },
      { thai: 'กินมาเยอะแล้ว แต่ของหวานต่ออีกนิดยังไหว', english: "I've already eaten a lot, but I can still handle a little dessert." },
      { thai: 'มางานตั้งแต่หกโมง อยู่ถึงเที่ยงคืนไม่ไหวหรอก', english: "I've been here since six. I can't stay until midnight." },
      { thai: 'เดินขึ้นเขาอีกกิโลเดียวฉันยังไหว', english: 'I can still handle one more kilometer uphill.' },
      { thai: 'ตากผ้าอีกสองรอบก็ยังไหว', english: 'I can still hang up two more loads of laundry.' },
      { thai: 'อุ้มลูกนานกว่านี้ไม่ไหวแล้ว แขนล้า', english: "I can't hold the baby any longer. My arms are tired." },
      { thai: 'เผ็ดระดับนี้ฉันไม่ไหวจริงๆ', english: "This level of spice is too much for me." },
    ],
  },
  superlative: {
    stage: 'A2.2',
    lessonTitle: 'Superlatives with ที่สุด',
    rows: [
      { thai: 'ร้านนี้ขายข้าวมันไก่อร่อยที่สุดแถวบ้าน', english: 'This shop has the best chicken rice in the neighborhood.' },
      { thai: 'วันนี้รถติดหนักที่สุดตั้งแต่ต้นเดือน', english: "Traffic was the worst it's been all month today." },
      { thai: 'ห้องนี้เงียบที่สุดในออฟฟิศ', english: 'This room is the quietest spot in the office.' },
      { thai: 'เธอเป็นคนมาถึงเร็วที่สุดในทีม', english: 'She got here earlier than anyone else on the team.' },
      { thai: 'ร้านนั้นปิดดึกที่สุดในย่านนี้', english: 'That shop stays open later than anywhere else around here.' },
      { thai: 'ข้อสอบวันนี้ยากที่สุดในเทอมนี้', english: "Today's exam was the hardest one this term." },
      { thai: 'ฉันชอบเสื้อตัวนี้ที่สุด เพราะใส่สบาย', english: "This is my favorite shirt because it's comfortable." },
      { thai: 'เดือนเมษาน่าจะร้อนที่สุดของปีแล้ว', english: 'April is probably the hottest month of the year.' },
      { thai: 'คาเฟ่นี้คนแน่นที่สุดช่วงบ่ายวันเสาร์', english: 'This cafe is busiest on Saturday afternoons.' },
      { thai: 'เขาพูดน้อยที่สุดในที่ประชุม แต่ตรงประเด็นที่สุด', english: 'He spoke the least in the meeting, but he was the most to the point.' },
      { thai: 'ทางนี้สั้นที่สุดถ้าจะเดินไปสถานี', english: 'This is the shortest way to walk to the station.' },
      { thai: 'โรงแรมนี้แพงที่สุดในบรรดาที่เราดูไว้', english: 'This is the most expensive hotel we looked at.' },
      { thai: 'เพื่อนคนนี้เข้าใจฉันดีที่สุด', english: 'This friend understands me best.' },
      { thai: 'ร้านผลไม้ตรงปากซอยขายมะม่วงหวานที่สุด', english: 'The fruit shop at the end of the alley sells the sweetest mangoes.' },
      { thai: 'เธอแต่งตัวเรียบที่สุดในกลุ่ม แต่ดูดีมาก', english: 'She was dressed the simplest in the group, but she looked great.' },
      { thai: 'วันนี้ฉันเหนื่อยที่สุดตั้งแต่กลับมาทำงาน', english: "This is the most tired I've felt since coming back to work." },
      { thai: 'เด็กคนนี้จำชื่อเพื่อนได้เร็วที่สุดในห้อง', english: 'This kid learns everyone’s name the fastest in the class.' },
      { thai: 'ห้องพักชั้นห้าน่าจะเย็นที่สุดตอนบ่าย', english: 'The room on the fifth floor is probably the coolest in the afternoon.' },
      { thai: 'เมนูนี้เผ็ดที่สุดในร้าน ถ้าไม่กินเผ็ดอย่าสั่ง', english: "This is the spiciest dish on the menu, so don't order it if you can't eat spicy food." },
      { thai: 'เขาตอบแชตช้าที่สุดเสมอ', english: "He's always the slowest one to reply to messages." },
      { thai: 'เช้านี้ตลาดสดคึกคักที่สุดก่อนเจ็ดโมง', english: 'The fresh market is most lively before seven in the morning.' },
      { thai: 'ฉันว่าแบบนี้ดูเข้ากับเธอที่สุด', english: 'I think this style suits you best.' },
      { thai: 'งานชิ้นนี้ใช้เวลานานที่สุด แต่ก็คุ้ม', english: 'This task took the longest, but it was worth it.' },
      { thai: 'สาขานี้บริการดีที่สุดเท่าที่ฉันเคยเจอ', english: 'This branch has the best service I’ve ever had.' },
      { thai: 'เธอเป็นคนใจเย็นที่สุดเวลาเกิดปัญหา', english: 'She’s the calmest person when something goes wrong.' },
    ],
  },
  'must-tong': {
    stage: 'A2.2',
    lessonTitle: 'Necessity with ต้อง',
    rows: [
      { thai: 'พรุ่งนี้ฉันต้องไปต่อใบขับขี่', english: "I have to renew my driver's license tomorrow." },
      { thai: 'ถ้าจะเข้าตึกนี้ ต้องแลกบัตรก่อน', english: 'You have to exchange your ID before entering this building.' },
      { thai: 'ยานี้ต้องกินหลังอาหาร', english: 'This medicine has to be taken after meals.' },
      { thai: 'นักเรียนต้องส่งงานก่อนห้าโมง', english: 'Students have to submit the assignment before five.' },
      { thai: 'เราต้องรีบออกแล้ว ไม่งั้นจะตกเครื่อง', english: "We have to leave now or we'll miss the flight." },
      { thai: 'ถ้าลืมพาสปอร์ต ก็ขึ้นเครื่องไม่ได้ ต้องกลับไปเอา', english: "If you forget your passport, you can't board. You have to go back for it." },
      { thai: 'ก่อนเปิดร้าน ฉันต้องเช็กสต๊อกก่อนทุกวัน', english: 'I have to check the stock every day before opening the shop.' },
      { thai: 'วันนี้ไม่อยากออกไปไหนเลย แต่ต้องไปทำฟัน', english: "I don't want to go anywhere today, but I have to go to the dentist." },
      { thai: 'ถ้าจะย้ายคอนโดเดือนหน้า เราต้องเริ่มแพ็กของแล้ว', english: "If we're moving next month, we have to start packing already." },
      { thai: 'เด็กๆ ต้องคาดเข็มขัดทุกครั้งเวลาขึ้นรถ', english: 'Kids have to wear a seat belt every time they get in the car.' },
      { thai: 'คืนนี้ฉันต้องอยู่ทำโอที', english: 'I have to work overtime tonight.' },
      { thai: 'ถ้ารถติดแบบนี้ เราต้องเปลี่ยนเส้นทาง', english: 'If traffic is this bad, we have to take another route.' },
      { thai: 'ก่อนส่งอีเมลนี้ คุณต้องเช็กชื่อผู้รับอีกที', english: "You need to check the recipient's name again before sending this email." },
      { thai: 'ถ้าจะสมัครงานนี้ ต้องมีประสบการณ์อย่างน้อยสองปี', english: 'You need at least two years of experience to apply for this job.' },
      { thai: 'ฉันต้องจ่ายค่าเช่าภายในวันศุกร์', english: 'I have to pay the rent by Friday.' },
      { thai: 'เขาต้องพาแม่ไปหาหมอแต่เช้า', english: 'He has to take his mom to the doctor first thing in the morning.' },
      { thai: 'เวลาทำกับข้าวเมนูนี้ ต้องหรี่ไฟลงหน่อย', english: 'You need to turn the heat down a bit when cooking this dish.' },
      { thai: 'ถ้าจะสอบใบขับขี่รอบนี้ ต้องอ่านป้ายจราจรให้แม่น', english: 'If you want to take the driving test this round, you really need to know the road signs.' },
      { thai: 'เราต้องโทรแจ้งลูกค้าก่อนเลื่อนนัด', english: 'We have to let the client know before moving the appointment.' },
      { thai: 'ถ้าไม่สบายแบบนี้ ต้องพักก่อน', english: 'If you feel this sick, you need to rest first.' },
      { thai: 'ฉันต้องลบรูปเก่าออกก่อน เมมเต็มแล้ว', english: 'I have to delete some old photos first. My storage is full.' },
      { thai: 'ก่อนเข้าห้องประชุม ต้องปิดเสียงโทรศัพท์', english: 'You have to silence your phone before going into the meeting.' },
      { thai: 'ถ้าจะให้ทันรอบหนัง เราต้องสั่งอาหารตอนนี้เลย', english: "If we want to make the movie on time, we need to order now." },
      { thai: 'พรุ่งนี้ต้องตื่นเช้าหน่อย เพราะมีประชุมเก้าโมง', english: "I have to wake up a little early tomorrow because I have a nine o'clock meeting." },
      { thai: 'ถ้าฝนยังไม่หยุด เราต้องเลื่อนทริปออกไป', english: "If the rain doesn't stop, we'll have to postpone the trip." },
    ],
  },
  'should-khuan': {
    stage: 'A2.2',
    lessonTitle: 'Advice and Expectation with ควร',
    rows: [
      { thai: 'ถ้าเหนื่อยมากก็ควรพักก่อน', english: "If you're really tired, you should rest first." },
      { thai: 'เราควรโทรจองโต๊ะก่อนเย็นวันศุกร์', english: 'We should book a table before Friday evening.' },
      { thai: 'เด็กเล็กควรนอนให้พอ', english: 'Young children should get enough sleep.' },
      { thai: 'คุณควรอ่านเงื่อนไขให้ครบก่อนกดยืนยัน', english: 'You should read all the conditions before confirming.' },
      { thai: 'ถ้าปวดหลังแบบนี้ ไม่ควรยกของหนัก', english: "If your back hurts like this, you shouldn't lift anything heavy." },
      { thai: 'เราควรออกจากบ้านเร็วหน่อย พรุ่งนี้น่าจะรถติด', english: 'We should leave home a bit early tomorrow. It will probably be busy on the roads.' },
      { thai: 'เธอควรคุยกับหัวหน้าตรงๆ มากกว่าเก็บไว้คนเดียว', english: 'She should talk to her boss directly instead of keeping it to herself.' },
      { thai: 'ก่อนกินยาใหม่ คุณควรถามเภสัชก่อน', english: 'You should ask the pharmacist before taking a new medicine.' },
      { thai: 'ถ้าไม่หิวก็ไม่ควรกินดึกทุกวัน', english: "If you're not hungry, you shouldn't eat late every day." },
      { thai: 'เราควรเก็บใบเสร็จไว้เผื่อต้องคืนของ', english: 'We should keep the receipt in case we need to return something.' },
      { thai: 'ถ้าฝนจะตก คุณควรพกร่มไปด้วย', english: 'If it looks like rain, you should bring an umbrella.' },
      { thai: 'เขาควรขอโทษตั้งแต่เมื่อวานแล้ว', english: 'He should have apologized yesterday already.' },
      { thai: 'คุณควรลองนอนให้ตรงเวลาสักอาทิตย์', english: 'You should try sleeping on a regular schedule for a week.' },
      { thai: 'ถ้าจะขึ้นดอยตอนเช้า เราควรเตรียมเสื้อกันหนาวไป', english: "If we're going up the mountain in the morning, we should bring warm clothes." },
      { thai: 'เราไม่ควรฝากกระเป๋าไว้ตรงนี้', english: "We shouldn't leave our bags here." },
      { thai: 'ก่อนส่งรายงาน คุณควรเช็กตัวเลขอีกครั้ง', english: 'You should check the numbers again before submitting the report.' },
      { thai: 'ถ้าไม่แน่ใจเส้นทาง ก็ควรเปิดแผนที่ไว้', english: "If you're not sure about the route, you should keep the map open." },
      { thai: 'เด็กๆ ควรล้างมือก่อนกินข้าว', english: 'Kids should wash their hands before eating.' },
      { thai: 'คุณควรบอกเขาล่วงหน้าถ้าจะไปสาย', english: "You should let him know ahead of time if you're going to be late." },
      { thai: 'ถ้ารู้สึกไม่ไหวจริงๆ ก็ควรหยุดพัก', english: "If you really can't handle it, you should take a break." },
      { thai: 'เราควรแบ่งงานกันให้ชัดกว่านี้', english: 'We should split the work more clearly.' },
      { thai: 'เขาไม่ควรขับรถตอนง่วงแบบนี้', english: "He shouldn't drive when he's this sleepy." },
      { thai: 'ถ้าจะไปทำพาสปอร์ต ควรไปแต่เช้า', english: "If you're going to get a passport, you should go early in the morning." },
      { thai: 'ฉันควรเริ่มเก็บเงินได้แล้ว', english: 'I really should start saving money.' },
      { thai: 'หลังออกกำลังกาย คุณควรดื่มน้ำเยอะๆ', english: 'You should drink plenty of water after exercising.' },
    ],
  },
  'prefix-naa-adjective': {
    stage: 'A2.2',
    lessonTitle: 'Descriptive Prefix น่า-',
    rows: [
      { thai: 'หนังเรื่องนี้น่ากลัวกว่าที่คิด', english: 'This movie is scarier than I expected.' },
      { thai: 'เด็กคนนั้นน่ารักมากเวลาเขายิ้ม', english: 'That kid is really adorable when he smiles.' },
      { thai: 'เรื่องที่เธอเล่าฟังเมื่อคืนฟังแล้วน่าสนใจมาก', english: 'What she told us last night was really interesting.' },
      { thai: 'ร้านนี้น่าเชื่อถือ รีวิวก็ดี คนก็แน่นทุกวัน', english: 'This place seems trustworthy. It has good reviews and it is busy every day.' },
      { thai: 'บรรยากาศร้านกาแฟตรงหัวมุมน่านั่งมาก', english: 'The cafe on the corner looks really inviting.' },
      { thai: 'เค้กชิ้นนี้น่ากินจนฉันอยากสั่งอีกชิ้น', english: 'This cake looks so good that I want to order another piece.' },
      { thai: 'ฝนตกทั้งวันแบบนี้น่าเบื่อเหมือนกัน', english: 'A whole day of rain like this is kind of boring.' },
      { thai: 'น่าเสียดายที่เราไปไม่ทันรอบสุดท้าย', english: "It's a pity we didn't make the last showing." },
      { thai: 'เขาเป็นคนคุยง่ายและน่าคบ', english: "He's easy to talk to and nice to be around." },
      { thai: 'รูปที่เธอถ่ายออกมาน่าประทับใจมาก', english: 'The photos she took turned out really impressive.' },
      { thai: 'เด็กคนนั้นน่าสงสาร ไม่มีใครมารับเลย', english: 'That kid is pitiful. No one came to pick them up.' },
      { thai: 'เรื่องนี้น่าแปลกตรงที่ไม่มีใครรู้มาก่อน', english: 'The strange thing about this is that nobody knew about it beforehand.' },
      { thai: 'ฉันว่าแผนนี้น่าจะเวิร์กนะ', english: 'I think this plan should work.' },
      { thai: 'เขาดูน่าจะถึงก่อนเรา', english: 'He looks like he’ll get there before us.' },
      { thai: 'เมนูใหม่ของร้านนี้น่าลองมาก', english: 'This shop’s new menu looks worth trying.' },
      { thai: 'ห้องนี้น่าอยู่กว่าที่คิด', english: 'This room feels more livable than I expected.' },
      { thai: 'เธอเป็นคนตรงเวลาและน่าไว้ใจ', english: 'She’s punctual and easy to trust.' },
      { thai: 'ข่าวนี้น่าตกใจพอสมควร', english: 'This news is pretty shocking.' },
      { thai: 'เสียงเพลงเบาๆ แบบนี้น่าฟังดี', english: 'Soft music like this is really pleasant to listen to.' },
      { thai: 'เด็กๆ กำลังอยู่ในวัยน่ารัก', english: 'The kids are at such a cute age right now.' },
      { thai: 'สาเหตุที่เขาลาออกก็น่าจะเรื่องเงิน', english: 'The reason he quit is probably money.' },
      { thai: 'แถวนี้น่าเดินตอนเย็นเพราะมีต้นไม้เยอะ', english: 'This area is nice to walk around in the evening because there are lots of trees.' },
      { thai: 'คำอธิบายของเขาน่าเชื่อมาก', english: 'His explanation sounds very believable.' },
      { thai: 'น่าอายเหมือนกันที่ฉันจำชื่อเขาไม่ได้', english: "It's a little embarrassing that I can't remember his name." },
      { thai: 'การแสดงเมื่อคืนนี้น่าดูมากจริงๆ', english: "Last night's performance was really worth watching." },
    ],
  },
  'feelings-rusuek': {
    stage: 'A2.2',
    lessonTitle: 'Feelings with รู้สึก',
    rows: [
      { thai: 'ฉันรู้สึกโล่งขึ้นหลังจากส่งรายงานเสร็จ', english: 'I felt relieved after I turned in the report.' },
      { thai: 'เขารู้สึกเกรงใจเวลาต้องรบกวนคนอื่น', english: 'He feels bad when he has to bother other people.' },
      { thai: 'วันนี้ฉันรู้สึกง่วงตั้งแต่เช้า', english: "I've felt sleepy since this morning." },
      { thai: 'เธอรู้สึกตื่นเต้นก่อนขึ้นเวที', english: 'She felt excited before going on stage.' },
      { thai: 'เรารู้สึกแปลกๆ ตอนกลับไปที่โรงเรียนเก่า', english: 'We felt a little strange going back to our old school.' },
      { thai: 'ฉันรู้สึกผิดที่ตอบเขาช้า', english: 'I felt bad for replying so late.' },
      { thai: 'เขารู้สึกมั่นใจขึ้นหลังซ้อมหลายรอบ', english: 'He felt more confident after practicing several times.' },
      { thai: 'แม่รู้สึกกังวลเพราะลูกยังไม่ถึงบ้าน', english: "Mom is worried because her child still isn't home." },
      { thai: 'ฉันรู้สึกอึดอัดเวลาอยู่ในห้องแคบๆ', english: 'I feel uncomfortable in very cramped rooms.' },
      { thai: 'เธอรู้สึกดีขึ้นหลังได้คุยกับเพื่อน', english: 'She felt better after talking to a friend.' },
      { thai: 'พอรู้ว่ารถไฟดีเลย์ ทุกคนก็รู้สึกเซ็งกันนิดหน่อย', english: 'Once they found out the train was delayed, everyone felt a little annoyed.' },
      { thai: 'ฉันรู้สึกตกใจตอนเห็นบิลค่าไฟเดือนนี้', english: 'I was shocked when I saw this month’s electricity bill.' },
      { thai: 'เขารู้สึกภูมิใจมากที่สอบผ่าน', english: 'He felt really proud that he passed the exam.' },
      { thai: 'ช่วงนี้ฉันรู้สึกหมดแรงง่าย', english: "Lately I've been getting tired very easily." },
      { thai: 'เธอรู้สึกสบายใจขึ้นหลังโทรหาที่บ้าน', english: 'She felt more at ease after calling home.' },
      { thai: 'ฉันรู้สึกไม่ค่อยมั่นใจเวลาใช้ภาษาไทยกับคนแปลกหน้า', english: "I don't feel very confident using Thai with strangers." },
      { thai: 'เขารู้สึกเสียดายที่ไม่ได้ไปงานนั้น', english: 'He regretted missing that event.' },
      { thai: 'เด็กๆ รู้สึกสนุกมากตอนเล่นน้ำ', english: 'The kids had a great time playing in the water.' },
      { thai: 'ฉันรู้สึกหงุดหงิดเวลารถติดนานๆ', english: 'I get irritated when traffic stays bad for too long.' },
      { thai: 'เธอรู้สึกโล่งใจที่ของยังไม่หาย', english: 'She was relieved that the item was not missing after all.' },
      { thai: 'หลังจากพักผ่อนเต็มที่ ฉันรู้สึกมีแรงขึ้นเยอะ', english: 'After getting proper rest, I felt much more energetic.' },
      { thai: 'เขารู้สึกกดดันก่อนพรีเซนต์งาน', english: 'He felt under pressure before the presentation.' },
      { thai: 'ฉันรู้สึกเกรงใจที่ให้เขารอนาน', english: 'I felt bad for making him wait so long.' },
      { thai: 'เธอรู้สึกอบอุ่นใจที่เพื่อนมารับ', english: 'She felt touched that her friend came to pick her up.' },
      { thai: 'พอฝนหยุดตก ทุกคนก็ดูรู้สึกดีขึ้น', english: 'Once the rain stopped, everyone seemed to feel better.' },
    ],
  },
  'try-lawng': {
    stage: 'A2.2',
    lessonTitle: 'Trying Something with ลอง',
    rows: [
      { thai: 'ลองโทรไปถามร้านก่อนก็ได้นะ', english: 'You could try calling the shop first.' },
      { thai: 'ฉันลองทำผัดกะเพราตามคลิปเมื่อวาน', english: 'I tried making pad kra pao from a video yesterday.' },
      { thai: 'ลองนั่งรถไฟฟ้าไปทำงานสักอาทิตย์ไหม', english: 'Why don’t you try taking the BTS to work for a week?' },
      { thai: 'เธอลองใส่รองเท้าคู่นี้แล้วเดินดูได้', english: 'Try these shoes on and walk around in them.' },
      { thai: 'ถ้าไอไม่หาย ลองเปลี่ยนยาแก้ไอดู', english: 'If the cough does not go away, try switching cough medicine.' },
      { thai: 'เขาลองพูดไทยกับแม่ค้าแล้วซื้อของได้จริงๆ', english: 'He tried speaking Thai with the vendor and actually managed to buy something.' },
      { thai: 'ลองพักหน้าจอสิบนาทีแล้วค่อยทำต่อ', english: 'Try taking a ten-minute screen break and then continue.' },
      { thai: 'ฉันลองตื่นเช้ากว่าเดิมหนึ่งชั่วโมงมาสามวันแล้ว', english: "I've been trying to wake up an hour earlier for three days." },
      { thai: 'ลองสั่งเมนูนี้ดู คนที่นี่ชอบกันมาก', english: 'Try ordering this dish. People here really like it.' },
      { thai: 'เธอลองตัดน้ำหวานไปหนึ่งเดือน', english: 'She tried cutting out sweet drinks for a month.' },
      { thai: 'ลองเปลี่ยนหมอนดู เผื่อคอจะไม่ปวด', english: 'Try changing your pillow. It might help your neck.' },
      { thai: 'เราลองขึ้นรถเมล์สายใหม่วันนี้', english: 'We tried taking the new bus line today.' },
      { thai: 'ถ้าเน็ตช้า ลองรีสตาร์ตเราเตอร์ก่อน', english: 'If the internet is slow, try restarting the router first.' },
      { thai: 'เขาลองขับรถเข้าซอยลัดแล้วถึงเร็วขึ้น', english: 'He tried taking the shortcut and got there faster.' },
      { thai: 'ลองคุยกับเขาตรงๆ ดูก่อนก็ได้', english: 'You could try talking to him directly first.' },
      { thai: 'ฉันลองทำบัญชีรายจ่ายทุกวันแล้วเห็นชัดขึ้นว่าเงินหายไปไหน', english: 'I tried tracking my expenses every day and could see more clearly where my money was going.' },
      { thai: 'เด็กๆ ลองปลูกโหระพาหลังบ้านกัน', english: 'The kids tried planting basil behind the house.' },
      { thai: 'ลองเปิดหน้าต่างดู เผื่อห้องจะเย็นลง', english: 'Try opening the window and see if the room cools down.' },
      { thai: 'เธอลองสมัครงานอีกที่หนึ่งเผื่อมีข่าวเร็วกว่า', english: 'She tried applying to another place in case they got back faster.' },
      { thai: 'ฉันลองทำผมทรงใหม่ก่อนงานแต่งเพื่อน', english: "I tried a new hairstyle before my friend's wedding." },
      { thai: 'เขาลองนอนเร็วขึ้นแต่ยังตื่นสายอยู่', english: 'He tried going to bed earlier, but he is still waking up late.' },
      { thai: 'ลองส่งข้อความไปก่อน เผื่อเขาประชุมอยู่', english: 'Try sending a message first in case he is in a meeting.' },
      { thai: 'เราลองใช้บัตรเติมเงินแทนเงินสดช่วงนี้', english: 'We have been trying a prepaid card instead of cash lately.' },
      { thai: 'ถ้าเครื่องยังไม่ติด ลองเสียบปลั๊กใหม่อีกที', english: "If the machine still won't start, try plugging it in again." },
      { thai: 'ฉันลองทำงานจากร้านกาแฟแล้วรู้สึกมีสมาธิกว่าอยู่บ้าน', english: 'I tried working from a cafe and felt more focused than at home.' },
    ],
  },
  'resultative-ok-samret': {
    stage: 'A2.2',
    lessonTitle: 'Resultative Verbs with ออก / สำเร็จ',
    rows: [
      { thai: 'ฉันนึกชื่อร้านนั้นออกแล้ว', english: 'I remember the name of that restaurant now.' },
      { thai: 'เขาเปิดฝาขวดนี้ไม่ออก', english: 'He cannot get this bottle open.' },
      { thai: 'ในที่สุดเราก็คิดทางแก้เรื่องนี้ออก', english: 'In the end, we figured out a solution to this problem.' },
      { thai: 'เด็กคนนี้อ่านคำนี้ออกแล้ว', english: 'This kid can read this word now.' },
      { thai: 'ฉันตอบคำถามข้อนี้ไม่ออกจริงๆ', english: 'I really cannot answer this question.' },
      { thai: 'เธอดึงลิ้นชักไม่ออก เพราะมันติด', english: "She can't pull the drawer open because it is stuck." },
      { thai: 'คำนี้ฉันยังออกเสียงไม่ค่อยออก', english: 'I still cannot pronounce this word very well.' },
      { thai: 'เขาแกะสติกเกอร์ออกหมดแล้ว', english: 'He peeled all the stickers off already.' },
      { thai: 'ในที่สุดเราก็ทำโปรเจกต์นี้สำเร็จ', english: 'In the end, we finished this project successfully.' },
      { thai: 'ฉันลบไฟล์เก่าออกจากคอมหมดแล้ว', english: 'I already deleted all the old files from the computer.' },
      { thai: 'น้องสาวฉันทำเค้กวันเกิดก้อนแรกสำเร็จแล้ว', english: 'My sister successfully made her first birthday cake.' },
      { thai: 'เราจองตั๋วรถไฟได้สำเร็จก่อนระบบล่ม', english: 'We managed to book the train tickets before the system crashed.' },
      { thai: 'เธออัปโหลดไฟล์ได้สำเร็จก่อนเที่ยงคืน', english: 'She managed to upload the file before midnight.' },
      { thai: 'ฉันประกอบชั้นวางของเสร็จเองได้', english: 'I managed to put the shelf together by myself.' },
      { thai: 'แม่ทำซอสสูตรนี้สำเร็จสักที', english: 'Mom finally got this sauce right.' },
      { thai: 'พอซ้อมมาหลายวัน เขาก็ออกเสียงชื่อนั้นได้แล้ว', english: 'After practicing for several days, he could finally pronounce that name.' },
      { thai: 'ฉันเพิ่งนึกคำตอบออกตอนอาบน้ำ', english: 'The answer came to me while I was in the shower.' },
      { thai: 'เราเปิดประตูออกได้แล้วหลังหากุญแจเจอ', english: 'We managed to get the door open once we found the key.' },
      { thai: 'น้องอ่านป้ายหน้าร้านออกแล้ว', english: 'My younger sibling can read the sign in front of the shop now.' },
      { thai: 'ฉันเขียนประโยคนี้ออก แต่ใช้เวลานานหน่อย', english: 'I managed to write this sentence, but it took a while.' },
      { thai: 'เขาพูดคำว่าขอโทษไม่ออก', english: "He couldn't bring himself to say sorry." },
      { thai: 'ในที่สุดเราก็จองโต๊ะได้สำเร็จทั้งที่สายไม่ว่างนานมาก', english: 'We finally managed to book a table even though the line was busy for a long time.' },
      { thai: 'แม่ปลูกมะเขือเทศในกระถางสำเร็จ', english: 'Mom successfully grew tomatoes in pots.' },
      { thai: 'พวกเขาช่วยกันคิดปัญหานี้ออก', english: 'They figured this problem out together.' },
      { thai: 'ฉันจำรหัสผ่านเก่าออกแล้ว', english: 'I remember my old password now.' },
    ],
  },
  'passive-tuuk': {
    stage: 'A2.2',
    lessonTitle: 'Passive with ถูก',
    rows: [
      { thai: 'กระเป๋าฉันถูกขโมยบนรถเมล์', english: 'My bag was stolen on the bus.' },
      { thai: 'เขาถูกตำหนิกลางที่ประชุม', english: 'He was criticized in the middle of the meeting.' },
      { thai: 'หนังสือเล่มนี้ถูกแปลเป็นหลายภาษา', english: 'This book was translated into many languages.' },
      { thai: 'ร้านนี้ถูกแนะนำในคู่มือท่องเที่ยว', english: 'This restaurant was recommended in a travel guide.' },
      { thai: 'จดหมายฉบับนี้ถูกส่งไปผิดที่', english: 'This letter was sent to the wrong place.' },
      { thai: 'เขาถูกเลือกเป็นตัวแทนห้อง', english: 'He was chosen as the class representative.' },
      { thai: 'โทรศัพท์ฉันถูกลืมไว้ในแท็กซี่', english: 'My phone was left in a taxi.' },
      { thai: 'พัสดุถูกส่งกลับเพราะไม่มีคนรับ', english: 'The package was sent back because nobody was there to receive it.' },
      { thai: 'เพื่อนฉันถูกบังคับให้ทำโอที', english: 'My friend was forced to work overtime.' },
      { thai: 'รถฉันถูกชนตอนจอดอยู่หน้าร้าน', english: 'My car was hit while it was parked in front of the shop.' },
      { thai: 'ชื่อฉันถูกสะกดผิดในใบเสร็จ', english: 'My name was misspelled on the receipt.' },
      { thai: 'ประชุมถูกเลื่อนไปบ่ายสาม', english: 'The meeting was moved to three in the afternoon.' },
      { thai: 'ห้องนี้ถูกจองเต็มตลอดสุดสัปดาห์', english: 'This room is fully booked all weekend.' },
      { thai: 'รูปนี้ถูกถ่ายตอนเราไปเชียงใหม่', english: 'This photo was taken when we went to Chiang Mai.' },
      { thai: 'เอกสารถูกส่งมาไม่ครบ', english: 'The documents were sent incomplete.' },
      { thai: 'คำขอของเราถูกปฏิเสธไปแล้ว', english: 'Our request was already rejected.' },
      { thai: 'ข้อความนั้นถูกลบก่อนที่ฉันจะได้อ่าน', english: 'That message was deleted before I could read it.' },
      { thai: 'นักเรียนคนนั้นถูกเรียกไปพบครูใหญ่', english: 'That student was called in to see the principal.' },
      { thai: 'ถนนเส้นนี้ถูกปิดเพราะมีงานวิ่ง', english: 'This road was closed because of a running event.' },
      { thai: 'โต๊ะตัวนี้ถูกย้ายไปห้องข้างๆ แล้ว', english: 'This table was moved to the room next door already.' },
      { thai: 'ร้านนี้ถูกวิจารณ์หนักหลังขึ้นราคา', english: 'This shop was heavily criticized after it raised its prices.' },
      { thai: 'หมายเลขคิวของฉันถูกเรียกไปแล้ว', english: 'My queue number was already called.' },
      { thai: 'รูปงานแต่งถูกอัปโหลดครบแล้ว', english: 'The wedding photos have all been uploaded.' },
      { thai: 'ออเดอร์ของลูกค้าถูกยกเลิกเมื่อเช้า', english: "The customer's order was canceled this morning." },
      { thai: 'ใบสมัครถูกส่งช้าไปหนึ่งวัน', english: 'The application was submitted one day late.' },
    ],
  },
  conditionals: {
    stage: 'A2.2',
    lessonTitle: 'Conditionals with ถ้า',
    rows: [
      { thai: 'ถ้าฝนตก ฉันจะไม่ไปตลาด', english: "If it rains, I won't go to the market." },
      { thai: 'ถ้าอ่านหนังสือสม่ำเสมอ ก็จะสอบผ่าน', english: "If you study regularly, you'll pass the exam." },
      { thai: 'ถ้าเขาตื่นสาย ก็จะไม่ทันรถเมล์', english: "If he wakes up late, he'll miss the bus." },
      { thai: 'ถ้าไปทะเลตอนเที่ยง ก็จะเจอแดดแรง', english: "If we go to the beach at noon, we'll be out in the strong sun." },
      { thai: 'ถ้าไม่กินข้าวเช้า จะหิวเร็ว', english: "If you don't eat breakfast, you'll get hungry quickly." },
      { thai: 'ถ้าทำการบ้านเสร็จ ก็จะได้ดูทีวี', english: 'If he finishes his homework, he can watch TV.' },
      { thai: 'ถ้าเธอมีเวลา ก็ไปช่วยฉันได้นะ', english: 'If you have time, you can come help me.' },
      { thai: 'ถ้าฉันทำงานเสร็จเร็ว ก็จะได้พัก', english: "If I finish work early, I'll get to rest." },
      { thai: 'ถ้าไม่โทรหาเขา เขาจะไม่รู้', english: "If you don't call him, he won't know." },
      { thai: 'ถ้าพรุ่งนี้อากาศดี เราจะไปเดินเล่น', english: "If the weather is good tomorrow, we'll go for a walk." },
      { thai: 'ถ้าเครื่องบินดีเลย์ เราจะต่อเครื่องไม่ทัน', english: "If the flight is delayed, we'll miss our connection." },
      { thai: 'ถ้าใส่เกลือเยอะเกินไป ซุปจะเค็มมาก', english: 'If you add too much salt, the soup will be way too salty.' },
      { thai: 'ถ้าไม่จองล่วงหน้า เราจะไม่ได้โต๊ะ', english: "If we don't book ahead, we won't get a table." },
      { thai: 'ถ้าฉันส่งรายงานไม่ทันวันศุกร์ หัวหน้าจะโกรธแน่', english: "If I don't submit the report by Friday, the boss will definitely be mad." },
      { thai: 'ถ้าพ่อแม่มาเยี่ยมสุดสัปดาห์นี้ เราจะไปวัดด้วยกัน', english: 'If my parents visit this weekend, we’ll go to the temple together.' },
      { thai: 'ถ้าสั่งตอนนี้ พัสดุจะมาถึงพรุ่งนี้', english: 'If you order now, the package will arrive tomorrow.' },
      { thai: 'ถ้าหากุญแจไม่เจอ จะเข้าบ้านไม่ได้นะ', english: "If you can't find your keys, you won't be able to get into the house." },
      { thai: 'ถ้าไม่กินยาตรงเวลา อาการจะไม่ดีขึ้น', english: "If you don't take your medicine on time, you won't get better." },
      { thai: 'ถ้าออกช่วงเวลาเร่งด่วน จะติดรถเป็นชั่วโมง', english: "If we leave during rush hour, we'll be stuck in traffic for hours." },
      { thai: 'ถ้าแอร์เสียคืนนี้ เราจะต้องไปนอนชั้นล่าง', english: 'If the air conditioner breaks tonight, we will have to sleep downstairs.' },
      { thai: 'ถ้าลืมบัตรพนักงาน ยามจะไม่ให้เข้าออฟฟิศ', english: "If you forget your staff card, the security guard won't let you into the office." },
      { thai: 'ถ้าวางนมไว้ข้างนอก นมจะเสีย', english: "If you leave the milk outside, it'll go bad." },
      { thai: 'ถ้าแบตโทรศัพท์หมด จะเรียกแท็กซี่ไม่ได้', english: "If your phone battery dies, you won't be able to call a taxi." },
      { thai: 'ถ้าไม่โอนเงินภายในคืนนี้ เขาจะยกเลิกออเดอร์', english: "If you don't transfer the money by tonight, they'll cancel the order." },
      { thai: 'ถ้าคืนนี้อากาศหนาวลง เธอจะต้องใส่แจ็กเก็ต', english: 'If it gets colder tonight, you’ll need a jacket.' },
    ],
  },
  'change-state-khuen-long': {
    stage: 'A2.2',
    lessonTitle: 'Change of State with ขึ้น / ลง',
    rows: [
      { thai: 'ค่าไฟขึ้นอีกแล้วช่วงนี้', english: 'Electricity bills have gone up again lately.' },
      { thai: 'หลังฝนหยุด อากาศเย็นลงหน่อย', english: 'The weather cooled down a bit after the rain stopped.' },
      { thai: 'เขารู้สึกดีขึ้นหลังได้พักสองวัน', english: 'He feels better after getting two days of rest.' },
      { thai: 'น้ำหนักเธอลดลงเร็วมากช่วงนี้', english: 'Her weight has been going down really quickly lately.' },
      { thai: 'พอได้ฟังเพลง เขาก็อารมณ์ดีขึ้น', english: 'Listening to music puts him in a better mood.' },
      { thai: 'ฉันรู้สึกแย่ลงหลังอ่านข่าวนั้น', english: 'I felt worse after reading that news.' },
      { thai: 'เธออ้วนขึ้นตั้งแต่เริ่มทำงานออฟฟิศ', english: 'She has put on weight since she started office work.' },
      { thai: 'เสียงเพลงดังขึ้นทุกทีหลังสี่ทุ่ม', english: 'The music gets louder and louder after ten at night.' },
      { thai: 'เข้าหน้าหนาวเมื่อไร อุณหภูมิก็ลดลงเยอะ', english: 'Once the cool season starts, the temperature drops a lot.' },
      { thai: 'เขาปรับตัวกับชีวิตในเมืองได้ดีขึ้น', english: 'He is getting better at adjusting to city life.' },
      { thai: 'หลังบ่ายสอง คนในร้านก็น้อยลง', english: 'There are fewer people in the shop after two in the afternoon.' },
      { thai: 'พอช่างล้างแอร์เสร็จ ห้องก็เย็นขึ้นเยอะ', english: 'The room got much cooler after the air conditioner was cleaned.' },
      { thai: 'เปลี่ยนแว่นใหม่แล้วมองชัดขึ้นเยอะ', english: 'I can see much more clearly after changing my glasses.' },
      { thai: 'ฝนตกหนักขึ้นตอนที่เรากำลังจะออกจากบ้าน', english: 'The rain got heavier just as we were about to leave home.' },
      { thai: 'ราคาผักลงนิดหน่อยอาทิตย์นี้', english: 'Vegetable prices went down a little this week.' },
      { thai: 'เด็กๆ เครียดขึ้นพอใกล้สอบ', english: 'The kids get more stressed as exams get closer.' },
      { thai: 'แผลดูดีขึ้นกว่าวานนี้', english: 'The wound looks better than it did yesterday.' },
      { thai: 'หลังหมดโปร คนซื้อน้อยลงทันที', english: 'After the promotion ended, fewer people were shopping right away.' },
      { thai: 'เปิดหน้าต่างแล้วกลิ่นอาหารเบาลง', english: 'Once we opened the window, the smell of food got lighter.' },
      { thai: 'พอรถไฟเข้าชานชาลา ชานชาลาก็แน่นขึ้นทันที', english: 'As soon as the train pulled in, the platform got crowded right away.' },
      { thai: 'เขาพูดคล่องขึ้นหลังซ้อมทุกวัน', english: 'He speaks more fluently after practicing every day.' },
      { thai: 'หลังฝนตกทั้งคืน ระดับน้ำในคลองสูงขึ้น', english: 'The water level in the canal rose after it rained all night.' },
      { thai: 'พอแบตใกล้หมด เครื่องก็ช้าลงมาก', english: 'When the battery gets low, the device slows down a lot.' },
      { thai: 'ค่าเช่าห้องขึ้นทุกปี', english: 'The rent goes up every year.' },
      { thai: 'หลังย้ายโต๊ะใหม่ งานก็ง่ายขึ้นนิดหน่อย', english: 'Work got a little easier after I moved desks.' },
    ],
  },
  'in-order-to-phuea': {
    stage: 'A2.2',
    lessonTitle: 'Purpose with เพื่อ / เพื่อจะ',
    rows: [
      { thai: 'ฉันไปธนาคารเพื่อจ่ายค่าเทอม', english: 'I went to the bank to pay my tuition.' },
      { thai: 'เขาโทรไปที่โรงแรมเพื่อยืนยันการจอง', english: 'He called the hotel to confirm the booking.' },
      { thai: 'เราออกจากบ้านเร็วเพื่อเลี่ยงรถติด', english: 'We left home early to avoid traffic.' },
      { thai: 'แม่แช่ข้าวเหนียวไว้เพื่อทำข้าวเหนียวมะม่วงพรุ่งนี้', english: 'Mom soaked the sticky rice to make mango sticky rice tomorrow.' },
      { thai: 'เธอเก็บใบเสร็จไว้เพื่อใช้ตอนคืนของ', english: 'She kept the receipt so she could return the item.' },
      { thai: 'ฉันอาบน้ำเร็วๆ เพื่อจะไปหาหมอให้ทัน', english: 'I hurried through my shower so I could make it to my doctor’s appointment on time.' },
      { thai: 'เราซื้อผลไม้ไปเพื่อเอาไปไหว้ยาย', english: 'We bought fruit to bring as an offering for Grandma.' },
      { thai: 'เขาเข้าออนไลน์แต่เช้าเพื่อส่งไฟล์ก่อนประชุม', english: 'He logged on early to send the file before the meeting.' },
      { thai: 'ฉันอ่านประกาศซ้ำอีกครั้งเพื่อจะได้ไม่กรอกฟอร์มผิด', english: "I read the notice again so I wouldn't fill out the form incorrectly." },
      { thai: 'พวกเขานัดเจอกันก่อนเพื่อเลือกของขวัญวันเกิดให้เพื่อน', english: 'They met up beforehand to choose a birthday gift for their friend.' },
      { thai: 'เธอพกเสื้อแจ็กเก็ตไปเพื่อจะได้ไม่หนาวบนรถ', english: "She brought a jacket so she wouldn't get cold on the bus." },
      { thai: 'ฉันล้างกล่องข้าวทันทีเพื่อไม่ให้มีกลิ่น', english: "I washed the lunch box right away so it wouldn't keep the smell." },
      { thai: 'เขาซื้อดอกไม้เพื่อขอโทษแฟน', english: 'He bought flowers to apologize to his girlfriend.' },
      { thai: 'เราจองโต๊ะล่วงหน้าเพื่อจะได้ไม่ต้องรอนาน', english: "We booked a table in advance so we wouldn't have to wait long." },
      { thai: 'เขาโหลดแผนที่ไว้เพื่อใช้ตอนเน็ตหลุด', english: 'He downloaded the map to use in case the internet stopped working.' },
      { thai: 'ฉันตั้งปลุกสองอันเพื่อจะได้ไม่ตื่นสาย', english: "I set two alarms so I wouldn't oversleep." },
      { thai: 'พ่อเติมน้ำมันเต็มถังเพื่อจะได้ขับออกต่างจังหวัดพรุ่งนี้', english: 'Dad filled up the tank so he could drive out of town tomorrow.' },
      { thai: 'เธอพกเงินสดไว้บ้างเพื่อขึ้นวินมอเตอร์ไซค์', english: 'She kept some cash on hand to pay for a motorcycle taxi.' },
      { thai: 'เราปิดหน้าต่างเพื่อไม่ให้ฝนสาดเข้า', english: "We closed the window so the rain wouldn't blow in." },
      { thai: 'ฉันเขียนรายการซื้อของไว้เพื่อจะได้ไม่ลืมอะไร', english: "I wrote a shopping list so I wouldn't forget anything." },
      { thai: 'เขาพาวเวอร์แบงก์ไปเพื่อชาร์จโทรศัพท์ระหว่างทาง', english: 'He brought a power bank to charge his phone on the way.' },
      { thai: 'แม่ทำกับข้าวไว้เยอะหน่อยเพื่อให้ฉันเอาไปกินกลางวัน', english: 'Mom cooked extra so I could take some for lunch.' },
      { thai: 'เรารีบกลับบ้านเพื่อรอช่างมาติดตั้งอินเทอร์เน็ต', english: 'We hurried home so we could be there when the technician installed the internet.' },
      { thai: 'เขาลงคอร์สสั้นๆ เพื่อเตรียมตัวสัมภาษณ์งาน', english: 'He took a short course to prepare for the job interview.' },
      { thai: 'ฉันซื้อเค้กมาเพื่อเซอร์ไพรส์น้องสาววันเกิด', english: 'I bought a cake to surprise my sister on her birthday.' },
    ],
  },
};

for (const [lessonId, lesson] of Object.entries(lessons)) {
  const target = path.join(outDir, `${lessonId}-kimi-final25-reviewed.json`);
  const payload = { lessonId, stage: lesson.stage, lessonTitle: lesson.lessonTitle, rows: lesson.rows };
  fs.writeFileSync(target, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');
}
